import { DEMO_CLINIC_ID, DEMO_EMAIL, DEMO_PHYSIOTHERAPIST_ID } from './demo.constants';
import {
  DemoDevice,
  DemoExercise,
  DemoFleetMetrics,
  DemoPatient,
  DemoPhysiotherapist,
  DemoClinic,
  DemoSessionHistoryItem,
  DemoTherapyOverview,
  DemoTreatmentPlan,
} from './demo.types';

function isoDaysAgo(days: number, hours = 0): string {
  return new Date(Date.now() - (days * 24 * 60 + hours * 60) * 60 * 1000).toISOString();
}

function isoDaysFromNow(days: number): string {
  return new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();
}

export const DEMO_EXERCISES: DemoExercise[] = [
  {
    id: 'demo-exercise-1',
    name: 'Flexión de codo asistida',
    description: 'Flexión controlada de codo con rango de movimiento progresivo.',
    bodyPart: 'ELBOW',
    movementType: 'FLEXION',
    videoUrl: null,
  },
  {
    id: 'demo-exercise-2',
    name: 'Extensión de codo',
    description: 'Extensión activa de codo hasta el rango prescrito.',
    bodyPart: 'ELBOW',
    movementType: 'EXTENSION',
    videoUrl: null,
  },
  {
    id: 'demo-exercise-3',
    name: 'Pronación de muñeca',
    description: 'Rotación de antebrazo hacia pronación con control de velocidad.',
    bodyPart: 'WRIST',
    movementType: 'PRONATION',
    videoUrl: null,
  },
  {
    id: 'demo-exercise-4',
    name: 'Supinación de muñeca',
    description: 'Rotación de antebrazo hacia supinación con control de velocidad.',
    bodyPart: 'WRIST',
    movementType: 'SUPINATION',
    videoUrl: null,
  },
  {
    id: 'demo-exercise-5',
    name: 'Flexión de muñeca',
    description: 'Flexión palmar de muñeca con carga progresiva.',
    bodyPart: 'WRIST',
    movementType: 'FLEXION',
    videoUrl: null,
  },
  {
    id: 'demo-exercise-6',
    name: 'Extensión de muñeca',
    description: 'Extensión dorsal de muñeca con carga progresiva.',
    bodyPart: 'WRIST',
    movementType: 'EXTENSION',
    videoUrl: null,
  },
];

export const DEMO_PHYSIOTHERAPIST: DemoPhysiotherapist = {
  id: DEMO_PHYSIOTHERAPIST_ID,
  userId: DEMO_PHYSIOTHERAPIST_ID,
  clinicId: DEMO_CLINIC_ID,
  fullName: 'Dra. Camila Rivas',
  specialty: 'Rehabilitación de miembro superior',
  email: DEMO_EMAIL,
  countryCode: '+51',
  phoneNumber: '987654321',
  licenseNumber: 'CFT-10234',
  professionalSummary:
    'Fisioterapeuta especializada en rehabilitación post-quirúrgica de codo y muñeca.',
  photoUrl: null,
  yearsOfExperience: 7,
  hireDate: isoDaysAgo(900),
  status: 'ACTIVE',
};

export const DEMO_CLINIC: DemoClinic = {
  id: DEMO_CLINIC_ID,
  legalName: 'Centro de Rehabilitación uFlex S.A.C.',
  commercialName: 'uFlex Rehab Center',
  ruc: '20601234567',
  email: 'contacto@uflexrehab.demo',
  countryCode: '+51',
  phoneNumber: '014567890',
  address: {
    countryCode: 'PE',
    region: 'Lima',
    city: 'Lima',
    addressLine1: 'Av. Rehabilitación 123',
    addressLine2: 'Piso 4',
    postalCode: '15001',
  },
};

export function createDemoPatients(): DemoPatient[] {
  return [
    {
      id: 'demo-patient-1',
      firstName: 'Valentina',
      lastName: 'Torres',
      dni: '71234567',
      birthDate: '1990-03-14',
      gender: 'FEMALE',
      email: 'valentina.torres@demo.dev',
      countryCode: '+51',
      phoneNumber: '911111111',
      medicalCondition: 'Post-quirúrgico de codo derecho, fractura de radio distal',
      assignedPhysiotherapistId: DEMO_PHYSIOTHERAPIST_ID,
      status: 'IN_TREATMENT',
      clinicId: DEMO_CLINIC_ID,
    },
    {
      id: 'demo-patient-2',
      firstName: 'Mateo',
      lastName: 'Salazar',
      dni: '72345678',
      birthDate: '1985-07-22',
      gender: 'MALE',
      email: 'mateo.salazar@demo.dev',
      countryCode: '+51',
      phoneNumber: '922222222',
      medicalCondition: 'Tendinitis de muñeca izquierda',
      assignedPhysiotherapistId: DEMO_PHYSIOTHERAPIST_ID,
      status: 'IN_TREATMENT',
      clinicId: DEMO_CLINIC_ID,
    },
    {
      id: 'demo-patient-3',
      firstName: 'Renata',
      lastName: 'Quispe',
      dni: '73456789',
      birthDate: '1998-11-02',
      gender: 'FEMALE',
      email: 'renata.quispe@demo.dev',
      countryCode: '+51',
      phoneNumber: '933333333',
      medicalCondition: 'Esguince de muñeca derecha',
      assignedPhysiotherapistId: DEMO_PHYSIOTHERAPIST_ID,
      status: 'REGISTERED',
      clinicId: DEMO_CLINIC_ID,
    },
    {
      id: 'demo-patient-4',
      firstName: 'Diego',
      lastName: 'Fernández',
      dni: '74567890',
      birthDate: '1979-01-30',
      gender: 'MALE',
      email: 'diego.fernandez@demo.dev',
      countryCode: '+51',
      phoneNumber: '944444444',
      medicalCondition: 'Rehabilitación post-artroscopia de codo',
      assignedPhysiotherapistId: DEMO_PHYSIOTHERAPIST_ID,
      status: 'COMPLETED',
      clinicId: DEMO_CLINIC_ID,
    },
    {
      id: 'demo-patient-5',
      firstName: 'Camila',
      lastName: 'Vega',
      dni: '75678901',
      birthDate: '2002-05-18',
      gender: 'FEMALE',
      email: 'camila.vega@demo.dev',
      countryCode: '+51',
      phoneNumber: '955555555',
      medicalCondition: 'Fractura de muñeca en consolidación',
      assignedPhysiotherapistId: DEMO_PHYSIOTHERAPIST_ID,
      status: 'DISCHARGED',
      clinicId: DEMO_CLINIC_ID,
    },
  ];
}

export function createDemoTreatmentPlans(): DemoTreatmentPlan[] {
  return [
    {
      id: 'demo-plan-1',
      patientId: 'demo-patient-1',
      name: 'Plan de recuperación de codo — fase 2',
      status: 'ACTIVE',
      period: { startsAt: isoDaysAgo(14), endsAt: isoDaysFromNow(28) },
      routines: [
        {
          id: 'demo-routine-1',
          name: 'Rutina matutina',
          order: 1,
          schedule: { dayOfWeek: 'MONDAY', scheduledTime: '08:00' },
          exerciseSeries: [
            {
              order: 1,
              exerciseId: 'demo-exercise-1',
              rangeOfMotionDegrees: 90,
              repetitions: 10,
              durationSeconds: 4,
              restDurationSeconds: 20,
            },
            {
              order: 2,
              exerciseId: 'demo-exercise-2',
              rangeOfMotionDegrees: 80,
              repetitions: 8,
              durationSeconds: 4,
              restDurationSeconds: 20,
            },
          ],
        },
      ],
    },
    {
      id: 'demo-plan-2',
      patientId: 'demo-patient-2',
      name: 'Plan de movilidad de muñeca',
      status: 'SCHEDULED',
      period: { startsAt: isoDaysFromNow(3), endsAt: isoDaysFromNow(45) },
      routines: [
        {
          id: 'demo-routine-2',
          name: 'Rutina de pronosupinación',
          order: 1,
          schedule: { dayOfWeek: 'TUESDAY', scheduledTime: '10:00' },
          exerciseSeries: [
            {
              order: 1,
              exerciseId: 'demo-exercise-3',
              rangeOfMotionDegrees: 70,
              repetitions: 12,
              durationSeconds: 3,
              restDurationSeconds: 15,
            },
            {
              order: 2,
              exerciseId: 'demo-exercise-4',
              rangeOfMotionDegrees: 70,
              repetitions: 12,
              durationSeconds: 3,
              restDurationSeconds: 15,
            },
          ],
        },
      ],
    },
    {
      id: 'demo-plan-3',
      patientId: 'demo-patient-4',
      name: 'Plan post-artroscopia — completado',
      status: 'COMPLETED',
      period: { startsAt: isoDaysAgo(60), endsAt: isoDaysAgo(10) },
      routines: [
        {
          id: 'demo-routine-3',
          name: 'Rutina de cierre',
          order: 1,
          schedule: { dayOfWeek: 'FRIDAY', scheduledTime: '09:00' },
          exerciseSeries: [
            {
              order: 1,
              exerciseId: 'demo-exercise-5',
              rangeOfMotionDegrees: 60,
              repetitions: 10,
              durationSeconds: 3,
              restDurationSeconds: 15,
            },
          ],
        },
      ],
    },
  ];
}

export function createDemoDevices(): DemoDevice[] {
  return [
    {
      id: 'demo-device-1',
      serialNumber: 'UFLEX-DEMO-0001',
      macAddress: 'AA:BB:CC:00:00:01',
      firmwareVersion: '1.4.2',
      batteryLevel: 82,
      model: 'uFlex Kit v2',
      advertisedName: 'uFlex-0001',
      calibrationStatus: 'VALID',
      status: 'ASSIGNED',
      lastSeenAt: isoDaysAgo(0, 0.1),
      clinicId: DEMO_CLINIC_ID,
      currentPatientId: 'demo-patient-1',
      currentPatientFullName: 'Valentina Torres',
      offline: false,
    },
    {
      id: 'demo-device-2',
      serialNumber: 'UFLEX-DEMO-0002',
      macAddress: 'AA:BB:CC:00:00:02',
      firmwareVersion: '1.4.2',
      batteryLevel: 45,
      model: 'uFlex Kit v2',
      advertisedName: 'uFlex-0002',
      calibrationStatus: 'VALID',
      status: 'AVAILABLE',
      lastSeenAt: isoDaysAgo(1),
      clinicId: DEMO_CLINIC_ID,
      currentPatientId: null,
      currentPatientFullName: null,
      offline: false,
    },
    {
      id: 'demo-device-3',
      serialNumber: 'UFLEX-DEMO-0003',
      macAddress: 'AA:BB:CC:00:00:03',
      firmwareVersion: '1.3.9',
      batteryLevel: 18,
      model: 'uFlex Kit v1',
      advertisedName: 'uFlex-0003',
      calibrationStatus: 'NEEDS_CALIBRATION',
      status: 'IN_MAINTENANCE',
      lastSeenAt: isoDaysAgo(9),
      clinicId: DEMO_CLINIC_ID,
      currentPatientId: null,
      currentPatientFullName: null,
      offline: true,
    },
    {
      id: 'demo-device-4',
      serialNumber: 'UFLEX-DEMO-0004',
      macAddress: 'AA:BB:CC:00:00:04',
      firmwareVersion: '1.4.2',
      batteryLevel: 97,
      model: 'uFlex Kit v2',
      advertisedName: 'uFlex-0004',
      calibrationStatus: 'VALID',
      status: 'IN_STOCK',
      lastSeenAt: null,
      clinicId: DEMO_CLINIC_ID,
      currentPatientId: null,
      currentPatientFullName: null,
      offline: false,
    },
  ];
}

export function computeDemoFleetMetrics(devices: DemoDevice[]): DemoFleetMetrics {
  return {
    total: devices.length,
    available: devices.filter((d) => d.status === 'AVAILABLE' || d.status === 'IN_STOCK').length,
    assigned: devices.filter((d) => d.status === 'ASSIGNED').length,
    inMaintenance: devices.filter((d) => d.status === 'IN_MAINTENANCE').length,
    lowBattery: devices.filter((d) => d.batteryLevel < 20).length,
    offline: devices.filter((d) => d.offline).length,
  };
}

export function createDemoTherapyOverview(): DemoTherapyOverview[] {
  return [
    {
      patientId: 'demo-patient-1',
      patientFullName: 'Valentina Torres',
      totalSessions: 12,
      completedSessions: 10,
      sessionsRequiringReview: 1,
      lastSessionAt: isoDaysAgo(0, 0.2),
      totalRepetitions: 340,
      goodRepetitions: 298,
      averageAchievedRom: 78.5,
      hasActiveSession: true,
    },
    {
      patientId: 'demo-patient-2',
      patientFullName: 'Mateo Salazar',
      totalSessions: 3,
      completedSessions: 3,
      sessionsRequiringReview: 0,
      lastSessionAt: isoDaysAgo(2),
      totalRepetitions: 96,
      goodRepetitions: 90,
      averageAchievedRom: 65.2,
      hasActiveSession: false,
    },
    {
      patientId: 'demo-patient-3',
      patientFullName: 'Renata Quispe',
      totalSessions: 0,
      completedSessions: 0,
      sessionsRequiringReview: 0,
      lastSessionAt: null,
      totalRepetitions: 0,
      goodRepetitions: 0,
      averageAchievedRom: null,
      hasActiveSession: false,
    },
    {
      patientId: 'demo-patient-4',
      patientFullName: 'Diego Fernández',
      totalSessions: 28,
      completedSessions: 28,
      sessionsRequiringReview: 2,
      lastSessionAt: isoDaysAgo(10),
      totalRepetitions: 890,
      goodRepetitions: 812,
      averageAchievedRom: 82.1,
      hasActiveSession: false,
    },
    {
      patientId: 'demo-patient-5',
      patientFullName: 'Camila Vega',
      totalSessions: 5,
      completedSessions: 4,
      sessionsRequiringReview: 0,
      lastSessionAt: isoDaysAgo(20),
      totalRepetitions: 150,
      goodRepetitions: 120,
      averageAchievedRom: 55.4,
      hasActiveSession: false,
    },
  ];
}

export function createDemoSessionHistory(): Record<string, DemoSessionHistoryItem[]> {
  return {
    'demo-patient-1': [
      {
        sessionId: 'demo-session-history-1',
        status: 'Completed',
        startedAt: isoDaysAgo(1),
        finalizedAt: isoDaysAgo(1, -0.3),
        treatmentPlanId: 'demo-plan-1',
        planningRoutineId: 'demo-routine-1',
        totalSeries: 2,
        completedSeries: 2,
        totalRepetitions: 18,
        goodRepetitions: 16,
        incompleteRepetitions: 2,
        unsafeRepetitions: 0,
        averageAchievedRom: 76.4,
        painLevel: 2,
        maxReportedPainLevel: 3,
        requiresClinicalReview: false,
        compensatoryMovementsDetected: 1,
      },
      {
        sessionId: 'demo-session-history-2',
        status: 'Completed',
        startedAt: isoDaysAgo(2),
        finalizedAt: isoDaysAgo(2, -0.3),
        treatmentPlanId: 'demo-plan-1',
        planningRoutineId: 'demo-routine-1',
        totalSeries: 2,
        completedSeries: 2,
        totalRepetitions: 18,
        goodRepetitions: 15,
        incompleteRepetitions: 3,
        unsafeRepetitions: 0,
        averageAchievedRom: 74.1,
        painLevel: 3,
        maxReportedPainLevel: 4,
        requiresClinicalReview: true,
        compensatoryMovementsDetected: 2,
      },
    ],
    'demo-patient-2': [
      {
        sessionId: 'demo-session-history-3',
        status: 'Completed',
        startedAt: isoDaysAgo(2),
        finalizedAt: isoDaysAgo(2, -0.25),
        treatmentPlanId: 'demo-plan-2',
        planningRoutineId: 'demo-routine-2',
        totalSeries: 2,
        completedSeries: 2,
        totalRepetitions: 24,
        goodRepetitions: 22,
        incompleteRepetitions: 2,
        unsafeRepetitions: 0,
        averageAchievedRom: 64.8,
        painLevel: 1,
        maxReportedPainLevel: 2,
        requiresClinicalReview: false,
        compensatoryMovementsDetected: 0,
      },
    ],
  };
}
