import { HttpClient } from '@angular/common/http';
import { catchError, map, Observable } from 'rxjs';
import { environment } from '../../../environments/environment';
import { buildApiUrl } from '../../shared/infrastructure/api-url';
import { ErrorHandlingEnabledBaseType } from '../../shared/infrastructure/error-handling-enabled-base-type';
import { TherapySessionAssembler } from './therapy-session.assembler';
import {
  TherapySessionHistoryItemResource,
  TherapySessionHistoryItemResponse,
} from './therapy-session.response';

const patientsApiEndpointUrl = buildApiUrl(
  environment.apiBaseUrl,
  environment.platformProviderPatientsEndpointPath,
);

/**
 * A patient's therapy-session history. Built from the patients endpoint path rather than a new
 * environment key, mirroring {@code TreatmentPlansByPatientApiEndpoint} — `environment.ts` is
 * generated by `scripts/generate-environment.mjs` on prestart/prebuild, so hand edits are lost.
 */
export class PatientTherapySessionsApiEndpoint extends ErrorHandlingEnabledBaseType {
  constructor(
    private http: HttpClient,
    private assembler: TherapySessionAssembler,
  ) {
    super();
  }

  /**
   * @param treatmentPlanId scopes the history to a single plan; omit for every session
   */
  getHistoryByPatient(
    patientId: string,
    treatmentPlanId?: string,
  ): Observable<TherapySessionHistoryItemResource[]> {
    const query = treatmentPlanId ? `?treatmentPlanId=${encodeURIComponent(treatmentPlanId)}` : '';
    return this.http
      .get<
        TherapySessionHistoryItemResponse[]
      >(`${patientsApiEndpointUrl}/${patientId}/therapy-sessions${query}`)
      .pipe(
        map((responses) =>
          responses.map((response) =>
            this.assembler.toTherapySessionHistoryItemResourceFromResponse(response),
          ),
        ),
        catchError(this.handleError('Failed to load therapy session history')),
      );
  }
}
